version: "3.9"

services:
  cotacao:
    image: magnaldomelo/coopersystem.challenge.microservice.b:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - cotacao

networks:
  cotacao:
    driver: bridge