version: "3.9"

services:
  microservice.a:
    image: magnaldomelo/microservice.a:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: microservice.a/Dockerfile
    ports:
      - "8181:8181"
    networks:
      - cotacao
  microservice.b:
    image: magnaldomelo/microservice.b:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: microservice.b/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - cotacao

networks:
  cotacao:
    driver: bridge

